server:
  port: 9000
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/v1/product/**, /api/v1/category/**, /api/v1/order/**, /api/v1/customer/**
        - id: recommendation-service
          uri: lb://recommendation-service
          predicates:
            - Path=/api/v1/recommendation/**
